version: '3.1'

services:

  db:
    image: nginx:latest
    restart: always
    ports:
      - "3366:3366"
      - "3377:3377"
      - "3388:3388"
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf"